import { v4 as uuidv4 } from 'uuid';

const data = [
    {
        id: uuidv4(),
        title: 'Snowman',
        visible: true,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 2,
        title: 'Snowman',
        visible: true,
        selected: false,
        team: 'red',
        assassin: false,
    },
    {
        id: 3,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'neutral',
        assassin: false,
    },
    {
        id: 4,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: null,
        assassin: false,
    },
    {
        id: 5,
        title: 'Snowman',
        visible: true,
        selected: false,
        team: null,
        assassin: true,
    },
    {
        id: 6,
        title: 'Snowman',
        visible: false,
        selected: true,
        team: null,
        assassin: false,
    },
    {
        id: 7,
        title: 'Snowman',
        visible: false,
        selected: true,
        team: 'neutral',
        assassin: false,
    },
    {
        id: 8,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 9,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 10,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 11,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 12,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 13,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 14,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 15,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 16,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 17,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 18,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 19,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 20,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 21,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 22,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 23,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 24,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
    {
        id: 25,
        title: 'Snowman',
        visible: false,
        selected: false,
        team: 'blue',
        assassin: false,
    },
];

export default data;
